spring.application.name=Frases
server.port=8084

spring.datasource.url=jdbc:postgresql://mx-central-1.4af2dfec-e3e9-4e8c-913e-a439a614a14d.aws.yugabyte.cloud:5433/Frases
spring.datasource.username=admin
spring.datasource.password=rLDjyUg-ZmZ0AzeEDXwHsW13BG1q59
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.jakarta.persistence.jdbc.url=${spring.datasource.url}
spring.jpa.properties.jakarta.persistence.jdbc.user=${spring.datasource.username}
spring.jpa.properties.jakarta.persistence.jdbc.password=${spring.datasource.password}
spring.jpa.properties.jakarta.persistence.jdbc.driver=${spring.datasource.driver-class-name}

spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
